services:
  - type: worker
    name: tictokbot
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: bash start.sh
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: GROUP_LINK
        sync: false
      - key: GROUP_USERNAME
        sync: false
